spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Manu4781!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true